make tlm_signal array iteration use auto instead of size_t
Addresses compiler error:

error: comparison of integer expressions of
different signedness: 'std::size_t' {aka 'long
unsigned int'} and 'int' [-Werror=sign-compare]

Signed-off-by: Eugene Cohen <quic_egmc@quicinc.com>